# Generated by Django 4.0.5 on 2022-07-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='point',
        ),
    ]
